# Setup
title:               Andrea Tontini personal homepage
description:         'Software Engineer specialized in Embedded System, Linux and Open Source Software.'
url:                 https://atontini.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Andrea Tontini

# Gems
plugins:
  - jekyll-paginate